name: Vercel Deploy

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number
      pnpm-version:
        required: true
        type: string
      is-prod:
        required: true
        type: boolean
        description: "True for prod, false for staging"
      infisical-project-slug:
        required: true
        type: string
        description: "The Infisical project slug"
      infisical-secret-path:
        required: true
        type: string
        description: "The path to secrets in Infisical"
    outputs:
      deployment-url:
        description: "The URL of the deployed application"
        value: ${{ jobs.deploy.outputs.deployment-url }}
    secrets:
      INFISICAL_CLIENT_ID:
        required: true
      INFISICAL_CLIENT_SECRET:
        required: true
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Vercel CLI
        run: pnpm install -g vercel@latest

      - name: Pull Vercel Config
        run: vercel pull --yes --environment=${{ inputs.is-prod && 'production' || 'preview' }} --token=$VERCEL_TOKEN

      - name: Pull Secrets from Infisical
        uses: infisical/secrets-action@v1.0.9
        with:
          env-slug: ${{ inputs.is-prod && 'prod' || 'dev' }}
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          project-slug: ${{ inputs.infisical-project-slug }}
          secret-path: ${{ inputs.infisical-secret-path }}

      - name: Build Artifact
        run: vercel build ${{ inputs.is-prod && '--prod' || '' }} --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        id: deploy
        run: |
          DEPLOYMENT_URL=$(vercel deploy --prebuilt ${{ inputs.is-prod && '--prod' || '' }} --archive=tgz --token=$VERCEL_TOKEN)
          echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
